jobs = [
    {
        title: "IT Tech",
        start_period: new Date("2024", "11"),
        end_period: new Date(),
        location: "Rexburg, ID",
        description: "Collaborated with a team of other techs to resolve technical issues in BYU-I's classrooms. Maintained and replaced hundreds of projectors, monitors, speakers, Crestron touchpanels, and control systems. Maintained and updated spreadsheets that listed the technical specs of each room on campus.",
        picture: "",
        alt: "",
        skills: ["IT Skills", "Team Collaborator", "Hard Worker", "Organizing"]
    },
    {
        title: "Student Sound Tech",
        start_period: new Date("2024", "11"),
        end_period: new Date("2025", "2"),
        location: "Rexburg, ID",
        description: "Worked on a team to provide audio during events at BYU-Idaho. Set up and took down audio equipment for 3-5 events per week. Learned how to set up and use a mixer.",
        picture: "",
        alt: "",
        skills: ["Audio Tech", "Team Collaborator", "Hard Worker"]
    },
    {
        title: "Missionary for the Church of Jesus Christ of Latter-Day Saints",
        start_period: new Date("2022", "7"),
        end_period: new Date("2024", "7"),
        location: "Arcadia, CA",
        description: "Went out and talked to people about our religion, in a variety of outdoor conditions. Worked with other missionaries and local leaders in order to more effectively find those that were receptive to our message. Performed service for others, from helping with a food bank to cleaning up a lawn to running a broadcast.",
        picture: "images/service.jpg",
        alt: "Picture of people gardening",
        skills: ["Team Player", "Effective Communicator", "Hard Worker", "Self-Starter"]
    },
    {
        title: "Afterschool Program Helper for the Oneida School District.",
        start_period: new Date("2021", "8"),
        end_period: new Date("2022", "3"),
        location: "Malad, ID",
        description: "Worked with a teacher to help 5th grade students with their homework, ranging from math to writing. Worked with other teachers and helpers in the program to put on activities for students from 1st to 5th grade. Made sure that students had fun and answered questions that they had.",
        picture: "",
        alt: "",
        skills: ["Effective Communicator", "Tutoring", "Organizing"]
    }, 
    {
        title: "Cafeteria Worker for the Oneida School District",
        start_period: new Date("2017", "0"),
        end_period: new Date("2022", "4"),
        location: "Malad, ID",
        description: "Served lunch to students of Malad Middle School for 2017-2018 and Malad High School for 2018-2020 and 2021-2022. Replenished food supply for other cafeteria workers as needed. Cleaned off tables after students were done eating and disposed of garbage generated by the students.",
        picture: "",
        alt: "",
        skills: ["Time Management", "Cleaning", "Team Player"]
    }
]
projects = [
    {
        title: "Advent of Code",
        description: "Complete the Advent of Code challenges during free time.",
        picture: "images/code.png",
        alt: "Image of Advent of Code code",
        skills: ["Python Programming", "Problem Solving", "Self Starter"]
    },
    {
        title: "Computer Building",
        description: "Researched, bought, and assembled the computer parts that would be best for my circumstances.",
        picture: "images/pc.jpg",
        alt: "Image of home computer",
        skills: ["Research", "Budgeting", "PC Building"]
    }
]
school = [
    {
        school_name:"BYU-Idaho",
        location: "Rexburg, ID",
        start_period: new Date("2024", "8"),
        end_period: new Date(),
        degrees: ["Bachelors in Computer Science", "Computer Programming Certificate", "Functional Programming Certificate"],
        picture: "images/byu-i-sign.jpg",
        alt: "Picture of BYU-I Logo",
        skills: ["Self-Starter", "Quick Learner", "Python Programming", "Website Development"]
    },
    {
        school_name:"Malad High School",
        location: "Malad, ID",
        start_period: new Date("2018", "7"),
        end_period: new Date("2022", "4"),
        degrees: ["Valedictorian", "SEITech Technology Pathway Certificate", "TestOut Certificate"],
        picture: "",
        alt: "",
        skills: ["Hard Worker" , "Team Player", "Computer Repair/Building", "Self-Starter", "Quick Learner" , "IT Training"]
    },
    {
        school_name:"Bridgerland Technical College",
        location: "Logan, UT",
        start_period: new Date("2019", "7"),
        end_period: new Date("2022", "4"),
        degrees: ["Basic Electrical Certificate", "PLC Certificate", "3D Modeling Certificate"],
        picture: "",
        alt: "",
        skills: ["Hard Worker", "Self-Starter"]
    }
]
extracurriculars = [
    {
        groupName: "Academic Decathalon",
        start_period: new Date("2018", "7"),
        end_period: new Date("2022", "4"),
        description: "Team at Malad High School. Participated for 3 years and was captain during senior year of high school.",
        picture: "",
        alt: "",
        skills: ["Leadership", "Team Player", "Quick Learner", "Effective Communicator"]
    },
    {
        groupName: "Computing Society",
        start_period: new Date("2024", "7"),
        end_period: new Date(),
        description: "CS group at BYUI. Learned more about computers and coding. Practiced skills to help me get a job",
        picture: "",
        alt: "",
        skills: ["Self-Starter", "Quick Learner", "Python Programming", "Effective Communicator"]
    },
    {
        groupName: "Game Development Society",
        start_period: new Date("2024", "7"),
        end_period: new Date("2024", "11"),
        description: "CS group at BYUI. Collaborated with others to make a game. Learned how to develop games in Unity.",
        picture: "",
        alt: "",
        skills: ["Team Player", "Contribute Ideas", "Perseverance"]
    },
    {
        groupName: "Blue Crew",
        start_period: new Date("2024", "7"),
        end_period: new Date(),
        description: "Volunteer organization at BYUI. Worked with others to set up and run activities at BYUI.",
        picture: "",
        alt: "",
        skills: ["Team Player", "Hard Worker", "Organizational Skills"]
    }
]

function get_date_difference(date1, date2){
    const ms1 = date1.getTime();
    const ms2 = date2.getTime();
    const diffMs = Math.abs(ms2 - ms1);
    const diffDays = diffMs / (1000 * 60 * 60 * 24);
    return Math.floor(diffDays);
}


function skills_to_html(list_of_skills){
    let html = "";
    list_of_skills.forEach(element => {
        html += `<li>${element}</li>`
    });
    return html;
}

function job_to_html(list_of_jobs){
    let html = ``;
    // Checks to see if there is a picture with the job
    list_of_jobs.forEach(job => {
        if (job.picture === ""){
            pic = ""
        }
        else{
            pic = `<img src=${job.picture} alt="${job.alt}"></img>`
        }
        // Converts the list of job objects to html code
        html += `<div class="job">
                    <h1>${job.title}</h1>
                    ${pic}
                    <h2>From ${job.start_period.toLocaleString("default", {month: 'long'})} ${job.start_period.getFullYear()} to ${job.end_period.toLocaleString("default", {month: 'long'})} ${job.end_period.getFullYear()} in ${job.location}</h2>
                    <p>${job.description}</p>
                    <button class="skills_button">Skills Learned</button>
                    <ul class="skills hide">${skills_to_html(job.skills)}</ul>
                </div>`
    });
    return html;
}

function school_to_html(list_of_schools){
    let html = ``;
    // Checks to see if there is a picture with the school
    list_of_schools.forEach(school => {
        if (school.picture === ""){
            pic = ""
        }
        else{
            pic = `<img src=${school.picture} alt="${school.alt}"></img>`
        }
        // Converts the list of school objects to html code
        html += `<div class="school">
                    <h1>${school.school_name} in ${school.location}</h1>
                    ${pic}
                    <h2>From ${school.start_period.toLocaleString("default", {month: 'long'})} ${school.start_period.getFullYear()} to ${school.end_period.toLocaleString("default", {month: 'long'})} ${school.end_period.getFullYear()} in ${school.location}</h2>
                    <p>Degrees and Certificates</p>
                    <ul class="degrees">${skills_to_html(school.degrees)}</ul>
                    <button class="skills_button">Skills Learned</button>
                    <ul class="skills hide">${skills_to_html(school.skills)}</ul>
                </div>`
    });
    return html;
}

function extra_to_html(list_of_extras){
    let html = ``;
    // Checks to see if there is a picture with the extracuriccular
    list_of_extras.forEach(extra => {
        if (extra.picture === ""){
            pic = ""
        }
        else{
            pic = `<img src=${extra.picture} alt="${extra.alt}"></img>`
        }
        // Converts the list of school objects to html code
        html += `<div class="extra">
                    <h1>${extra.groupName}</h1>
                    ${pic}
                    <h2>From ${extra.start_period.toLocaleString("default", {month: 'long'})} ${extra.start_period.getFullYear()} to ${extra.end_period.toLocaleString("default", {month: 'long'})} ${extra.end_period.getFullYear()}</h2>
                    <p>${extra.description}</p>
                    
                    <button class="skills_button">Skills Learned</button>
                    <ul class="skills hide">${skills_to_html(extra.skills)}</ul>
                </div>`
    });
    return html;
}

function project_to_html(list_of_projects){
    let html = ``;
        list_of_projects.forEach(project => {
        if (project.picture === ""){
            pic = ""
        }
        else{
            pic = `<img src=${project.picture} alt="${project.alt}"></img>`
        }
        html += `<div class="project">
                    <h1>${project.title}</h1>
                    <p>${project.description}</p>
                    ${pic}
                    <button class="skills_button">Skills Learned</button>
                    <ul class="skills hide">${skills_to_html(project.skills)}</ul>

                </div>`
    });
    return html;
}

function hideSkills(e){
    const to_toggle = e.target.closest(".extra, .project, .job, .school").querySelector(".skills")
    to_toggle.classList.toggle("hide")
};

const currentPath = window.location.pathname;

if (currentPath === "/portfolio/experience.html" || currentPath === "/experience.html"){
    document.querySelector(".work").innerHTML += job_to_html(jobs);
    document.querySelector(".schooling").innerHTML += school_to_html(school);
}
if (currentPath === "/portfolio/skills.html" || currentPath === "/skills.html"){
document.querySelector(".extra_container").innerHTML += extra_to_html(extracurriculars);
document.querySelector(".projects").innerHTML += project_to_html(projects);
}

const skills_to_hide = document.querySelectorAll(".skills_button");
skills_to_hide.forEach(skill => {
    skill.addEventListener("click", hideSkills)

})
